export const FETCH_DETAILS = 'FETCH_DETAILS';

export const OPEN_PAPER_ADDER = 'OPEN_PAPER_ADDER';
export const CLOSE_PAPER_ADDER = 'CLOSE_PAPER_ADDER';

export const HIGHLIGHT_PAPER_NODE = 'HIGHLIGHT_PAPER_NODE';