export const FETCH_DETAILS = 'FETCH_DETAILS';

export const OPEN_PAPER_ADDER = 'OPEN_PAPER_ADDER';
export const CLOSE_PAPER_ADDER = 'CLOSE_PAPER_ADDER';

export const SET_ADDED_PAPER = 'SET_ADDED_PAPER';
export const SET_CHOSEN_PAPER = 'SET_CHOSEN_PAPER';
export const SET_SEARCHED_PAPERS = 'SET_SEARCHED_PAPERS';