export const CLEAR_NODES = 'CLEAR_NODES';
export const SET_ELEMENTS = 'SET_ELEMENTS';
export const SET_ERROR = 'SET_ERROR';

export const FETCH_DETAILS = 'FETCH_DETAILS';


export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';

export const OPEN_PAPER_ADDER = 'OPEN_PAPER_ADDER';
export const CLOSE_PAPER_ADDER = 'CLOSE_PAPER_ADDER';

export const BEYOND_ACCURACY_PAPER_ADDED = 'BEYOND_ACCURACY_PAPER_ADDED';